### ISSUE TITLE
Release 'External Drafts' plugin to Statamic Marketplace 

### ISSUE THREAD

**Issue by edalzell** [transformstudios/statamic-drafts#1]
Hey @edalzell I'd like to release the 'External Drafts' add-on for $15 per site. I can have @hollychovan create the matching assets to get it posted on the marketplace.

**Comment by edalzell** [comment]
From https://github.com/transformstudios/simple/issues/92

On this now, @hollychovan please provide assets. I'll create on Marketplace but not publish until assets are in.

@edalzell Can you please update the plugins (both drafts and events) so in the Addons Developer Column area it says Transform Studios please.

Also please see issue #93 before deploying since there seems to be a bug preventing it from working in production.

**Comment by edalzell** [comment]
@hollychovan just in case when I moved this issue you didn't see this, we need the assets for https://statamic.com/seller/products/drafts/edit

**Comment by adnankussair** [comment]
@hollychovan Let's get Erin assets for this plugin before you jump onto the Hub Foundation tasks.

@edalzell @hollychovan What do you think about naming:

- Drafts
- Draft Links
- External Drafts
- Draft Review

Ever wished you had the ability to share a draft entry (both collection entries and pages) with external contributors without them needing a control panel login and password? Well this does just that. Add an entry, set its status to draft, and save. When you go back and visit the entry you will notice a dropdown option next to the Draft toggle which generates a draft url for you to share with your lovely editor or contributor. Easy peasy lemon squeezy.

- Image snazzy bg (something to do with lemons? :P) with title of addon
- Image (image of dropdown showing the Draft Link)

**Comment by hollychovan** [comment]
I like just Drafts. It goes nicely with our one name theme so far. lol. I’ll get on the graphic.

Holly Chovan
P (916) 273.8716 <tel:9162738716> 			 
1209 Pleasant Grove Blvd.
Roseville, CA 95678 
  <https://transformstudios.com/>

**Comment by hollychovan** [comment]
Hey @edalzell I added the description and the images to Drafts!

**Comment by edalzell** [comment]
Launched! 

https://statamic.com/marketplace/addons/drafts

@adnankussair let's get the word out...commence twittering!

**Comment by adnankussair** [comment]
@edalzell The readme/description is generating without bullets and missing an image on both the events plugin and the drafts plugin. Any chance you can fix. before sharing. Thanks! :)

**Comment by edalzell** [comment]
ya the drafts image should come along shortly when the marketplace refreshes...caching (sigh).

I'll fix the others.

**Comment by edalzell** [comment]
Fixed and I've asked Jason to give the Marketplace a kick to pop those changes loose
