### ISSUE TITLE
Port to V3 (DO THIS)

### ISSUE THREAD

**Issue by adnankussair** [transformstudios/statamic-drafts#3]
Two options here. I think we ask the gents to consider adding this as a native function of Statamic V3. If they say yes, then Whoot! If not, it's an easy and simple plugin to port over.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2mt8v)

**Comment by adnankussair** [comment]
@edalzell Okay let's release v3. Please use whatever artwork you already have for v2 that is still applicable and we can loop back and update possibly with a new name if needed and also new graphics.

**Comment by fitzage** [comment]
I feel a bit like I’m jumping into a private conversation, but when you do get this done, is it going to support the new revisions feature also, or just draft pages? Or do you know yet?

**Comment by adnankussair** [comment]
@fitzage We launched drafts (now review) and posted a formal announcement today. See here: https://twitter.com/trnsfm/status/1374064344783319050

And it supports both Revisions AND Drafts. Whoot!
