### ISSUE TITLE
Drafts + Localization not compatible

### ISSUE THREAD

**Issue by adnankussair** [transformstudios/statamic-drafts#4]
See the drama in full action here:

<img width="561" alt="Screen Shot 2020-07-12 at 12 13 16 PM" src="https://user-images.githubusercontent.com/239259/87254736-80b8dc00-c439-11ea-9396-a6409f85ef2f.png">

**Comment by edalzell** [comment]
It's called Abstract Art @adnankussair

**Comment by adnankussair** [comment]
Closing, Review for V3 is localizable.
